name: Setup
description: Setup Node.js and install dependencies

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc
    - name: Install dependencies
      run: npm ci
      shell: bash
    - name: Install example dependencies
      run: npm ci --prefix example
      shell: bash
